# **Pandas LAB**

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Get the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [ ]:
users=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep='|',index_col='user_id')

### Step 4. See the first 25 entries

In [ ]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [ ]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [ ]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [ ]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [ ]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 10. What is the data type of each column?

In [ ]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [ ]:
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [ ]:
len(users['occupation'].unique())

21

### Step 13. What is the most frequent occupation?

In [ ]:
users['occupation'].value_counts()[0:1]

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

## **Group by Operations**

### Count the number of users in each occupation.

In [ ]:
users['age'].groupby(users['occupation']).count()

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
Name: age, dtype: int64

### Calculate the average age of users by gender.

In [ ]:
users['age'].groupby(users['gender']).mean()

gender
F    33.813187
M    34.149254
Name: age, dtype: float64

### Find the minimum, maximum, and average age for each occupation.

In [ ]:
users['age'].groupby(users['occupation']).agg(['min','max','mean'])

               min  max       mean
occupation
administrator   21   70  38.746835
artist          19   48  31.392857
doctor          28   64  43.571429
educator        23   63  42.010526
engineer        22   70  36.388060
entertainment   15   50  29.222222
executive       22   69  38.718750
healthcare      22   62  41.562500
homemaker       20   50  32.571429
lawyer          21   53  36.750000
librarian       23   69  40.000000
marketing       24   55  37.615385
none            11   55  26.555556
other           13   64  34.523810
programmer      20   63  33.121212
retired         51   73  63.071429
salesman        18   66  35.666667
scientist       23   55  35.548387
student          7   42  22.081633
technician      21   55  33.148148
writer          18   60  36.311111

## **Filtering**

### Filter the dataset to show only female users.

In [ ]:
users[users['gender'] == 'F']

         age gender  occupation zip_code
user_id
2         53      F       other    94043
5         33      F       other    15213
11        39      F       other    30329
12        28      F       other    06405
15        49      F    educator    97301
...      ...    ...         ...      ...
925       18      F    salesman    49036
930       28      F   scientist    07310
938       38      F  technician    55038
939       26      F     student    33319
942       48      F   librarian    78209

[273 rows x 4 columns]

### Filter the dataset to show users who are either students or educators.

In [ ]:
users[users['occupation'].isin(['student','educator'])]

         age gender occupation zip_code
user_id
9         29      M    student    01002
13        47      M   educator    29206
15        49      F   educator    97301
30         7      M    student    55436
32        28      F    student    78741
...      ...    ...        ...      ...
933       28      M    student    48105
937       48      M   educator    98072
939       26      F    student    33319
941       20      M    student    97229
943       22      M    student    77841

[291 rows x 4 columns]

### Filter the dataset to show female users who are in their 20s (20-29).

In [ ]:
users[(users['gender']=='F') & (users['age'].isin(range(20,30)))]

         age gender     occupation zip_code
user_id
12        28      F          other    06405
24        21      F         artist    94533
32        28      F        student    78741
35        20      F      homemaker    42459
38        28      F          other    54467
...      ...    ...            ...      ...
917       22      F        student    20006
921       20      F        student    98801
922       29      F  administrator    21114
930       28      F      scientist    07310
939       26      F        student    33319

[85 rows x 4 columns]

### Filter the dataset to find users from California (zip codes starting with '9')

In [ ]:
users[users['zip_code'].str.startswith('9')] #.str vectorize string across entire series

         age gender     occupation zip_code
user_id
2         53      F          other    94043
6         42      M      executive    98101
7         57      M  administrator    91344
10        53      M         lawyer    90703
15        49      F       educator    97301
...      ...    ...            ...      ...
902       45      F         artist    97203
920       30      F         artist    90008
921       20      F        student    98801
937       48      M       educator    98072
941       20      M        student    97229

[170 rows x 4 columns]

### Create a pivot table showing the count of users by occupation and age decade.
#### age decade: 27 years old --> 20s decade

In [ ]:
users['age_decade'] = (users['age'] // 10 * 10).astype(int).astype(str) + 's'
pivot_t = users.pivot_table(index='occupation',columns='age_decade',values='age',             
     aggfunc='count',fill_value=0)
pivot_t

age_decade     0s  10s  20s  30s  40s  50s  60s  70s
occupation
administrator   0    0   19   26   20   12    1    1
artist          0    1   12    9    6    0    0    0
doctor          0    0    2    0    3    1    1    0
educator        0    0   12   30   25   23    5    0
engineer        0    0   23   22   14    5    2    1
entertainment   0    2    8    5    2    1    0    0
executive       0    0    7   11   11    2    1    0
healthcare      0    0    4    1    7    3    1    0
homemaker       0    0    3    2    1    1    0    0
lawyer          0    0    4    4    1    3    0    0
librarian       0    0   11   15   13   11    1    0
marketing       0    0    5   12    4    5    0    0
none            0    3    2    3    0    1    0    0
other           0    4   38   29   22   11    1    0
programmer      0    0   30   21   10    3    2    0
retired         0    0    0    0    0    2   10    2
salesman        0    1    2    6    1    1    1    0
scientist       0    0    8   14    8    1    0    0
student         1   63  116   14    2    0    0    0
technician      0    0   12    8    5    2    0    0
writer          0    2   14    9   13    6    1    0