# Pandas Lab — Selection, Indexing & Filtration

---
This lab contains **2 exercises** to practice:
- `Series` and `DataFrame` selection
- Label-based indexing with `.loc`
- Positional indexing with `.iloc`
- Boolean masking & filtration

---
## Exercise 1 — Patient Blood Sugar Readings (Series)

A Series of glucose readings (mg/dL) for 10 patients, indexed by patient name.

In [3]:
import pandas as pd

blood_sugar = pd.Series(
        [82, 145, 200, 310, 95, 178, 260, 110, 340, 88],
        index=["Ali", "Sara", "Omar", "Mona", "Khaled",
               "Nour", "Tamer", "Hana", "Ramy", "Dina"],
        name="glucose_mg_dl"
)

print(blood_sugar)

Ali        82
Sara      145
Omar      200
Mona      310
Khaled     95
Nour      178
Tamer     260
Hana      110
Ramy      340
Dina       88
Name: glucose_mg_dl, dtype: int64

### Task 1.1 — Label-Based Selection
Select **Omar's** glucose reading using his name as a label.

In [6]:
blood_sugar['Omar']

np.int64(200)

### Task 1.2 — Positional Indexing
Select the **first 4 patients** using positional indexing.

In [47]:
blood_sugar.iloc[0:4]

Ali      82
Sara    145
Omar    200
Mona    310
Name: glucose_mg_dl, dtype: int64

### Task 1.3 — Boolean Masking
Filter patients whose glucose is **above 200** (diabetic range).  
How many patients fall in this range?

In [48]:
blood_sugar[blood_sugar> 200]

Mona     310
Tamer    260
Ramy     340
Name: glucose_mg_dl, dtype: int64

In [49]:
(blood_sugar> 200).sum()

np.int64(3)

### Task 1.4 — Fancy Indexing
Select readings for **Sara, Nour, and Dina** using a list of labels in a single line.

In [50]:
blood_sugar[['Sara','Nour','Dina']]

Sara    145
Nour    178
Dina     88
Name: glucose_mg_dl, dtype: int64

---
## Exercise 2 — Hospital Encounters (DataFrame)

A DataFrame of patient hospital encounters. The index is set to `encounter_id`.

| encounter_id | patient_name | age_group | time_in_hospital | num_medications | readmitted |
|---|---|---|---|---|---|
| 1001 | Ali Hassan | [30-40) | 3 | 12 | No |
| 1002 | Sara Nader | [60-70) | 7 | 21 | >30 |
| 1003 | Omar Fathi | [50-60) | 2 | 8 | No |
| 1004 | Mona Said | [70-80) | 11 | 30 | <30 |
| 1005 | Khaled Zaki | [40-50) | 5 | 15 | No |
| 1006 | Nour Adel | [60-70) | 9 | 25 | <30 |
| 1007 | Tamer Wael | [20-30) | 1 | 5 | No |

In [21]:
data = {
    "encounter_id":    [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    "patient_name":    ["Ali Hassan", "Sara Nader", "Omar Fathi",
                        "Mona Said", "Khaled Zaki", "Nour Adel", "Tamer Wael"],
    "age_group":       ["[30-40)", "[60-70)", "[50-60)", "[70-80)",
                        "[40-50)", "[60-70)", "[20-30)"],
    "time_in_hospital": [3, 7, 2, 11, 5, 9, 1],
    "num_medications":  [12, 21, 8, 30, 15, 25, 5],
    "readmitted":       ["No", ">30", "No", "<30", "No", "<30", "No"]
}

df = pd.DataFrame(data)
df = df.set_index("encounter_id")  # encounter_id becomes the index

df

,patient_name,age_group,time_in_hospital,num_medications,readmitted
encounter_id,,,,,
1001,Ali Hassan,[30-40),3,12,No
1002,Sara Nader,[60-70),7,21,>30
1003,Omar Fathi,[50-60),2,8,No
1004,Mona Said,[70-80),11,30,<30
1005,Khaled Zaki,[40-50),5,15,No
1006,Nour Adel,[60-70),9,25,<30
1007,Tamer Wael,[20-30),1,5,No

### Task 2.1 — Column Selection
Select **only** the `patient_name` and `readmitted` columns for all rows.

In [51]:
df[['patient_name','readmitted']]

             patient_name readmitted
encounter_id
1001           Ali Hassan         No
1002           Sara Nader        >30
1003           Omar Fathi         No
1004            Mona Said        <30
1005          Khaled Zaki         No
1006            Nour Adel        <30
1007           Tamer Wael         No

### Task 2.2 — Row Selection with `.loc`
Using `.loc`, retrieve the complete row for encounter **1004** (Mona Said).

In [53]:
df.loc[1004,:]

patient_name        Mona Said
age_group             [70-80)
time_in_hospital           11
num_medications            30
readmitted                <30
Name: 1004, dtype: object

### Task 2.3 — Positional Slicing with `.iloc`
Using `.iloc`, retrieve the **last 3 rows** and only the **first 2 columns**.

In [54]:
df.iloc[4:,:2]

             patient_name age_group
encounter_id
1005          Khaled Zaki   [40-50)
1006            Nour Adel   [60-70)
1007           Tamer Wael   [20-30)

### Task 2.4 — Combined Boolean Filtration
Filter patients who were **readmitted in under 30 days** AND spent **more than 5 days** in hospital.  
Show only their `patient_name` and `time_in_hospital`.

In [55]:
df.loc[(df['readmitted'] == '<30') & (df['time_in_hospital'] > 5),['patient_name','time_in_hospital']]

             patient_name  time_in_hospital
encounter_id
1004            Mona Said                11
1006            Nour Adel                 9

# Drop col without changing axis

In [43]:
df.drop(columns='readmitted')

             patient_name age_group  time_in_hospital  num_medications
encounter_id
1001           Ali Hassan   [30-40)                 3               12
1002           Sara Nader   [60-70)                 7               21
1003           Omar Fathi   [50-60)                 2                8
1004            Mona Said   [70-80)                11               30
1005          Khaled Zaki   [40-50)                 5               15
1006            Nour Adel   [60-70)                 9               25
1007           Tamer Wael   [20-30)                 1                5

# Drop columns and rows

In [56]:
df.drop(columns='readmitted',index=[1005,1002])

             patient_name age_group  time_in_hospital  num_medications
encounter_id
1001           Ali Hassan   [30-40)                 3               12
1003           Omar Fathi   [50-60)                 2                8
1004            Mona Said   [70-80)                11               30
1006            Nour Adel   [60-70)                 9               25
1007           Tamer Wael   [20-30)                 1                5